name: cell-factory-design-course
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - jupyterlab
  - ipykernel
  - pip:
      - -r requirements.txt
      - bibtexparser<2  # maintainers only: render_refs.py
